### ISSUE TITLE
Enchants not compatible with enchanted books ~ will not work with PiggyCrates

### ISSUE THREAD

**Issue by xDanub** [DaPigGuy/PiggyCustomEnchants#207]
Please make sure your issue complies with these guidelines:
- * [x] Server Software must be the official PMMP w/o vanilla patching plugins (i.e. TeaSpoon)
- * [x] Issue must have not been reported previously
- * [x] Make sure you are on the latest version of PMMP & PiggyCustomEnchants
- * [x] Have a detailed title, like "CustomEnchants::getName() must be..."
- * [x] If possible, provide crashdumps/errors related to the issue.

#### **General**
 I expected the books in PiggyCrates when configured to have an enchantment on them to be enchanted and able to be drag and dropped onto a tool, weapon, or armor piece.

#### **Version:**

- PiggyCustomEnchants: 1.4.6

- PMMP: 3.9.0

#### **Steps to Reproduce the Issue**

1. install PiggyCe and PiggyCrates
2. Configure the crates to have an enchanted book with any custom enchant on it.
3. Open that crate until you get the book.

**Comment by Aericio** [comment]
You can only enchant one book at a time. If more than one book is being enchanted for the same enchant, then nothing will happen. 

Example:
* hold two books (stacked) in your hand
* `/ce enchant explosive 1` 
* enchant will not apply

```yaml
  common:
    drops:
      - name: "Book"
        id: 340
        meta: 0
        amount: 1
        chance: 100
        enchantments:
          explosive:
            level: 1
    amount: 1
    particle: lava
    delay: 0.25
    block: "173:0"
```
